import {Dimensions, Platform, StyleSheet} from 'react-native';
import {moderateScale, scale, verticalScale} from 'react-native-size-matters';
import {colorList, elevationCard, FONT_SIZE, LINE_HEIGHT} from '../../styles/global.styles';

export const styles = StyleSheet.create({
  //Header Styles
  HeaderContainer: {},
  HeaderImage: {
    width: 115,
    height: 32,
    resizeMode: 'contain',
  },
  HeaderDropdownWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 5,
    marginLeft: 5,
  },
  HeaderDropdownText: {
    fontWeight: '600',
    fontSize: FONT_SIZE.md,
    lineHeight: LINE_HEIGHT.md,
    color: colorList.dark,
    marginRight: 4,
  },
  HeaderDropdownIcon: {},
  //End
  counterContainer: {
    borderRadius: 12,
    padding: 15,
    width: Dimensions.get('screen').width * 0.43,
    ...elevationCard,
  },
  counterNumber: {
    fontSize: FONT_SIZE.display,
    lineHeight: LINE_HEIGHT.display,
    fontWeight: '600',
    color: colorList.white,
    marginBottom: 8,
  },
  counterLabel: {
    fontSize: FONT_SIZE.lg,
    lineHeight: LINE_HEIGHT.lg,
    fontWeight: '500',
    color: colorList.white,
  },
  counterNumber1: {
    fontSize: FONT_SIZE.display,
    lineHeight: LINE_HEIGHT.display,
    fontWeight: '600',
    color: colorList.Black,
    marginBottom: 8,
  },
  counterLabel1: {
    fontSize: FONT_SIZE.lg,
    lineHeight: LINE_HEIGHT.lg,
    fontWeight: '500',
    color: colorList.Grey1,
  },
  upcommingAppoinmentsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
    marginBottom: 16,
  },
  upcommingAppoinmentsHeaderText: {
    fontSize: FONT_SIZE.xxl,
    fontWeight: '700',
    lineHeight: LINE_HEIGHT.xl,
    color: colorList.dark,
  },
  upcommingAppoinmentsViewAll: {
    fontSize: FONT_SIZE.md,
    fontWeight: '500',
    lineHeight: LINE_HEIGHT.md,
    color: colorList.Grey1,
    textDecorationLine: 'underline',
    paddingBottom: 5,
  },
  appoinmentContainer: {
    marginVertical: verticalScale(6),
    backgroundColor: colorList.white,
    borderRadius: scale(14),
    paddingHorizontal: scale(14),
    paddingVertical: verticalScale(12),
    borderWidth: 1,
    borderColor: colorList.Grey5,
    overflow: 'hidden',
    ...elevationCard,
  },
  appoinmentHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: verticalScale(10),
    gap: scale(8),
  },
  appoinmentStatusChip: {
    flexShrink: 1,
    maxWidth: '62%',
    paddingHorizontal: scale(10),
    paddingVertical: verticalScale(4),
    borderRadius: scale(20),
  },
  appoinmentStatusChipText: {
    fontSize: moderateScale(10),
    fontWeight: '700',
    textTransform: 'capitalize',
    lineHeight: moderateScale(12),
    ...(Platform.OS === 'android' && {includeFontPadding: false}),
  },
  appoinmentCancelButton: {
    flexShrink: 0,
    paddingHorizontal: scale(10),
    paddingVertical: verticalScale(4),
    borderRadius: scale(20),
    borderWidth: 1,
    borderColor: colorList.palette.error.main,
    backgroundColor: colorList.palette.error.light,
  },
  appoinmentCancelButtonText: {
    color: colorList.palette.error.main,
    fontSize: moderateScale(10),
    fontWeight: '600',
    lineHeight: moderateScale(12),
  },
  appoinmentPatientRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: scale(10),
    marginBottom: verticalScale(10),
  },
  appoinmentPatientAvatar: {
    borderWidth: 1,
    borderColor: colorList.Grey4,
    backgroundColor: colorList.Grey5,
  },
  appoinmentPatientInfo: {
    flex: 1,
    minWidth: 0,
  },
  appoinmentNameLabel: {
    fontSize: moderateScale(10),
    fontWeight: '500',
    lineHeight: moderateScale(12),
    color: colorList.Grey1,
    letterSpacing: 0.2,
  },
  appoinmentNameText: {
    fontSize: moderateScale(14),
    fontWeight: '700',
    lineHeight: moderateScale(18),
    marginTop: verticalScale(2),
    color: colorList.dark,
  },
  appoinmentActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(6),
    flexShrink: 0,
  },
  appoinmentIconButton: {
    width: scale(36),
    height: scale(36),
    borderRadius: scale(18),
    backgroundColor: colorList.Grey5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  appoinmentIconButtonPrimary: {
    backgroundColor: colorList.primary,
  },
  appoinmentMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colorList.blue_900,
    borderRadius: scale(10),
    paddingVertical: verticalScale(8),
    paddingHorizontal: scale(10),
    marginBottom: verticalScale(10),
  },
  appoinmentMetaItem: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    minWidth: 0,
    gap: scale(6),
  },
  appoinmentMetaDivider: {
    width: 1,
    height: verticalScale(18),
    backgroundColor: colorList.Grey4,
    marginHorizontal: scale(8),
  },
  appoinmentDate: {
    flex: 1,
    fontWeight: '600',
    fontSize: moderateScale(12),
    lineHeight: moderateScale(14),
    color: colorList.dark,
  },
  appoinmentTime: {
    flex: 1,
    fontWeight: '600',
    fontSize: moderateScale(12),
    lineHeight: moderateScale(14),
    color: colorList.dark,
  },
  appoinmentFooterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: scale(8),
    paddingTop: verticalScale(10),
    borderTopWidth: 1,
    borderTopColor: colorList.Grey5,
  },
  appoinmentDoctorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    minWidth: 0,
    gap: scale(8),
  },
  appoinmentDoctorAvatar: {
    width: scale(36),
    height: scale(36),
    borderRadius: scale(18),
    backgroundColor: colorList.Grey5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  appoinmentToLabelTextContainer: {
    flex: 1,
    minWidth: 0,
  },
  appoinmentToLabel: {
    fontSize: moderateScale(9),
    lineHeight: moderateScale(12),
    fontWeight: '500',
    color: colorList.Grey1,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  appoinmentToText: {
    fontSize: moderateScale(12),
    lineHeight: moderateScale(17),
    fontWeight: '600',
    color: colorList.dark,
    marginTop: verticalScale(1),
  },
  appoinmentQueueBadge: {
    flexShrink: 0,
    paddingHorizontal: scale(10),
    paddingVertical: verticalScale(5),
    borderRadius: scale(20),
    backgroundColor: colorList.Grey5,
  },
  appoinmentQueueBadgeText: {
    fontSize: moderateScale(9),
    fontWeight: '700',
    textAlign: 'center',
    textTransform: 'capitalize',
    lineHeight: moderateScale(12),
  },
  appoinmentQueueModalDivider: {
    borderBottomWidth: 1,
    marginVertical: verticalScale(15),
    borderColor: colorList.Grey3,
    width: '100%',
  },
  appoinmentQueueModalContent: {
    width: Dimensions.get('screen').width * 0.5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  appoinmentQueueModalOption: {
    width: '100%',
    paddingHorizontal: scale(12),
    paddingVertical: verticalScale(10),
    borderWidth: 0.2,
    borderRadius: scale(8),
    marginVertical: verticalScale(5),
    borderColor: colorList.Grey3,
  },
  appoinmentQueueModalOptionText: {
    textAlign: 'center',
    textTransform: 'capitalize',
    color: colorList.Grey1,
    fontSize: moderateScale(12),
  },
  appoinmentCancelModal: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  appoinmentCancelModalContent: {
    backgroundColor: colorList.white,
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: verticalScale(200),
    width: Dimensions.get('screen').width * 0.8,
    borderRadius: scale(8),
    paddingVertical: verticalScale(12),
  },
  appoinmentCancelModalTitle: {
    paddingVertical: verticalScale(5),
    fontSize: moderateScale(12),
    fontWeight: '600',
    color: colorList.dark,
  },
  appoinmentCancelModalBody: {
    width: '80%',
  },
  appoinmentCancelRequiredText: {
    color: colorList.red,
    fontSize: moderateScale(10),
    marginTop: verticalScale(4),
  },
  appoinmentCancelModalActions: {
    flexDirection: 'row',
    marginVertical: verticalScale(15),
    justifyContent: 'space-between',
  },
});
